import React from 'react';
import { Bot, ShieldAlert, X, Activity, BrainCircuit } from 'lucide-react';

interface AboutAIModalProps {
  onClose: () => void;
}

const AboutAIModal: React.FC<AboutAIModalProps> = ({ onClose }) => {
  return (
    <div className="fixed inset-0 bg-black/90 z-[1400] flex items-center justify-center p-4 backdrop-blur-md">
      <div className="bg-gray-900 border-2 border-cyan-500 rounded-lg w-full max-w-2xl shadow-[0_0_30px_rgba(6,182,212,0.2)] flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="bg-cyan-900/50 p-4 flex items-center justify-between shrink-0 border-b border-cyan-500/50">
          <div className="flex items-center gap-3">
            <Bot className="text-cyan-400 h-8 w-8" />
            <div>
              <h2 className="text-white font-bold text-xl uppercase tracking-wider">AI Defense Assistant</h2>
              <p className="text-cyan-400 text-xs font-mono">SYSTEM STATUS: ONLINE // MONITORING</p>
            </div>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
            <X size={24} />
          </button>
        </div>

        <div className="p-6 overflow-y-auto space-y-6 text-gray-300 custom-scrollbar">
          
          <section>
            <h3 className="text-yellow-500 font-bold uppercase flex items-center gap-2 mb-2">
              <BrainCircuit size={18} /> Core Directive
            </h3>
            <p className="text-sm leading-relaxed">
              The AI Defense Assistant is an autonomous agent integrated into the Szczecin Defense Network. 
              Its primary role is to <strong>analyze unstructured data</strong> (news feeds, geographical data, user reports) 
              to provide real-time situational awareness for civil defense purposes.
            </p>
          </section>

          <section className="bg-gray-800/50 p-4 rounded border border-gray-700">
            <h3 className="text-red-500 font-bold uppercase flex items-center gap-2 mb-3">
              <Activity size={18} /> Heatmap Generation Logic
            </h3>
            <div className="space-y-3 text-sm">
              <p>
                The "Threat Heatmap" layer is dynamic. It is not generated by live sensors, but by <strong>AI analysis</strong> of the following risk vectors in the context of Szczecin:
              </p>
              <ul className="list-disc pl-5 space-y-1 text-gray-400">
                <li><strong>Strategic Infrastructure:</strong> Key targets including the <em>Port of Szczecin</em>, <em>Szczecin Główny</em> (Rail Hub), and critical bridges.</li>
                <li><strong>Industrial Hazards:</strong> Proximity to chemical transport routes (specifically transport related to Police Chemical Plants) and fuel depots.</li>
                <li><strong>Population Density:</strong> Analysis of potential choke points during mass evacuation (e.g., Trasa Zamkowa, Wyzwolenia).</li>
              </ul>
              <div className="mt-3 text-xs border-l-2 border-red-500 pl-2 text-red-300">
                <strong>Current Analysis Focus:</strong> The AI is currently weighting "Industrial Accidents" and "Transport Congestion" as high-probability risks for the region.
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-yellow-500 font-bold uppercase flex items-center gap-2 mb-2">
              <ShieldAlert size={18} /> Automated Moderation
            </h3>
            <p className="text-sm leading-relaxed">
              Every marker added by the community is scanned by the AI. It filters out spam, irrelevant data, or commercial content, ensuring that only valid 
              <strong> Evacuation Points, Shelters, and Medical Stations</strong> are displayed on the public map.
            </p>
          </section>

          <div className="bg-yellow-900/20 border border-yellow-600/50 p-4 rounded text-xs text-yellow-200/80">
            <strong className="block text-yellow-500 mb-1 uppercase">⚠️ System Disclaimer</strong>
            This tool is powered by Gemini AI. While it strives for accuracy, it is a simulation for community preparedness and awareness. 
            <strong>Always follow official instructions from the Rządowe Centrum Bezpieczeństwa (RCB) and local emergency services (112).</strong> 
            The "Heatmap" represents <em>potential</em> risk zones based on strategic logic, not an official government warning.
          </div>

        </div>
      </div>
    </div>
  );
};

export default AboutAIModal;